import "./globals.css";
import React, { useState } from "react";
import type { Metadata } from "next";
import { Inter, League_Spartan } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const spartan = League_Spartan({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-mode="dark">
      <body className={`${inter.className} bg-slate-50 dark:bg-slate-900`}>
        {children}
      </body>
    </html>
  );
}
