import Link from "next/link";
import React, { useState } from "react";
import type { Metadata } from "next";
import { Inter, League_Spartan } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-mode="dark">
      <body className={`${inter.className} bg-slate-50 dark:bg-slate-900`}>
        <Sidebar />
        <main>{children}</main>
      </body>
    </html>
  );
}
